import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import { bodyContainer } from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
			<body className={inter.className}>
				<div className={bodyContainer}>
					<Header />
					{children}
					<Footer />

				</div>

				</body>
    </html>
  );
}
